title: "Causal Discovery from Temporal Data"
description: "KDD 2023 Tutorial <br/>
Chang Gong, Di Yao, Chuzhe Zhang, Wenbin Li and Jingping Bi"
header_text: KDD 2023 Tutorial
theme: jekyll-theme-slate
